/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { LandNFT__factory } from "./LandNFT__factory";
export { LandRegistry__factory } from "./LandRegistry__factory";
