/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace LandRegistry {
  export type LandParcelStruct = {
    parcelId: BigNumberish;
    owner: AddressLike;
    location: string;
    area: BigNumberish;
    documentCID: string;
    isRegistered: boolean;
    registeredAt: BigNumberish;
    lastTransferAt: BigNumberish;
  };

  export type LandParcelStructOutput = [
    parcelId: bigint,
    owner: string,
    location: string,
    area: bigint,
    documentCID: string,
    isRegistered: boolean,
    registeredAt: bigint,
    lastTransferAt: bigint
  ] & {
    parcelId: bigint;
    owner: string;
    location: string;
    area: bigint;
    documentCID: string;
    isRegistered: boolean;
    registeredAt: bigint;
    lastTransferAt: bigint;
  };
}

export interface LandRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ADMIN_ROLE"
      | "DEFAULT_ADMIN_ROLE"
      | "REGISTRAR_ROLE"
      | "addRegistrar"
      | "getOwnershipHistory"
      | "getParcelDetails"
      | "getParcelsByOwner"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "isAdmin"
      | "isRegistrar"
      | "landNFT"
      | "ownerParcels"
      | "parcelCount"
      | "parcelHistory"
      | "parcels"
      | "registerLand"
      | "removeRegistrar"
      | "renounceRole"
      | "revokeRole"
      | "supportsInterface"
      | "transferOwnership"
      | "verifyOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "LandRegistered"
      | "OwnershipTransferred"
      | "RegistrarAdded"
      | "RegistrarRemoved"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REGISTRAR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addRegistrar",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getOwnershipHistory",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getParcelDetails",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getParcelsByOwner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isRegistrar",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "landNFT", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ownerParcels",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "parcelCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "parcelHistory",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "parcels",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerLand",
    values: [AddressLike, string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "removeRegistrar",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyOwnership",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "ADMIN_ROLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REGISTRAR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addRegistrar",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOwnershipHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getParcelDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getParcelsByOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isAdmin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isRegistrar",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "landNFT", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "ownerParcels",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "parcelCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "parcelHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "parcels", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerLand",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeRegistrar",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyOwnership",
    data: BytesLike
  ): Result;
}

export namespace LandRegisteredEvent {
  export type InputTuple = [
    parcelId: BigNumberish,
    owner: AddressLike,
    location: string,
    area: BigNumberish,
    documentCID: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    parcelId: bigint,
    owner: string,
    location: string,
    area: bigint,
    documentCID: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    parcelId: bigint;
    owner: string;
    location: string;
    area: bigint;
    documentCID: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [
    parcelId: BigNumberish,
    previousOwner: AddressLike,
    newOwner: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    parcelId: bigint,
    previousOwner: string,
    newOwner: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    parcelId: bigint;
    previousOwner: string;
    newOwner: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RegistrarAddedEvent {
  export type InputTuple = [registrar: AddressLike, addedBy: AddressLike];
  export type OutputTuple = [registrar: string, addedBy: string];
  export interface OutputObject {
    registrar: string;
    addedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RegistrarRemovedEvent {
  export type InputTuple = [registrar: AddressLike, removedBy: AddressLike];
  export type OutputTuple = [registrar: string, removedBy: string];
  export interface OutputObject {
    registrar: string;
    removedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LandRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): LandRegistry;
  waitForDeployment(): Promise<this>;

  interface: LandRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  REGISTRAR_ROLE: TypedContractMethod<[], [string], "view">;

  addRegistrar: TypedContractMethod<
    [_registrar: AddressLike],
    [void],
    "nonpayable"
  >;

  getOwnershipHistory: TypedContractMethod<
    [_parcelId: BigNumberish],
    [string[]],
    "view"
  >;

  getParcelDetails: TypedContractMethod<
    [_parcelId: BigNumberish],
    [LandRegistry.LandParcelStructOutput],
    "view"
  >;

  getParcelsByOwner: TypedContractMethod<
    [_owner: AddressLike],
    [bigint[]],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  isAdmin: TypedContractMethod<[_addr: AddressLike], [boolean], "view">;

  isRegistrar: TypedContractMethod<[_addr: AddressLike], [boolean], "view">;

  landNFT: TypedContractMethod<[], [string], "view">;

  ownerParcels: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  parcelCount: TypedContractMethod<[], [bigint], "view">;

  parcelHistory: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;

  parcels: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, string, boolean, bigint, bigint] & {
        parcelId: bigint;
        owner: string;
        location: string;
        area: bigint;
        documentCID: string;
        isRegistered: boolean;
        registeredAt: bigint;
        lastTransferAt: bigint;
      }
    ],
    "view"
  >;

  registerLand: TypedContractMethod<
    [
      _owner: AddressLike,
      _location: string,
      _area: BigNumberish,
      _documentCID: string
    ],
    [bigint],
    "nonpayable"
  >;

  removeRegistrar: TypedContractMethod<
    [_registrar: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [_parcelId: BigNumberish, _newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  verifyOwnership: TypedContractMethod<
    [_parcelId: BigNumberish],
    [
      [string, string, bigint, string] & {
        owner: string;
        location: string;
        area: bigint;
        documentCID: string;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "REGISTRAR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "addRegistrar"
  ): TypedContractMethod<[_registrar: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getOwnershipHistory"
  ): TypedContractMethod<[_parcelId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "getParcelDetails"
  ): TypedContractMethod<
    [_parcelId: BigNumberish],
    [LandRegistry.LandParcelStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getParcelsByOwner"
  ): TypedContractMethod<[_owner: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isAdmin"
  ): TypedContractMethod<[_addr: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isRegistrar"
  ): TypedContractMethod<[_addr: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "landNFT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ownerParcels"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "parcelCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "parcelHistory"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "parcels"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, string, boolean, bigint, bigint] & {
        parcelId: bigint;
        owner: string;
        location: string;
        area: bigint;
        documentCID: string;
        isRegistered: boolean;
        registeredAt: bigint;
        lastTransferAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerLand"
  ): TypedContractMethod<
    [
      _owner: AddressLike,
      _location: string,
      _area: BigNumberish,
      _documentCID: string
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeRegistrar"
  ): TypedContractMethod<[_registrar: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<
    [_parcelId: BigNumberish, _newOwner: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyOwnership"
  ): TypedContractMethod<
    [_parcelId: BigNumberish],
    [
      [string, string, bigint, string] & {
        owner: string;
        location: string;
        area: bigint;
        documentCID: string;
      }
    ],
    "view"
  >;

  getEvent(
    key: "LandRegistered"
  ): TypedContractEvent<
    LandRegisteredEvent.InputTuple,
    LandRegisteredEvent.OutputTuple,
    LandRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RegistrarAdded"
  ): TypedContractEvent<
    RegistrarAddedEvent.InputTuple,
    RegistrarAddedEvent.OutputTuple,
    RegistrarAddedEvent.OutputObject
  >;
  getEvent(
    key: "RegistrarRemoved"
  ): TypedContractEvent<
    RegistrarRemovedEvent.InputTuple,
    RegistrarRemovedEvent.OutputTuple,
    RegistrarRemovedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;

  filters: {
    "LandRegistered(uint256,address,string,uint256,string,uint256)": TypedContractEvent<
      LandRegisteredEvent.InputTuple,
      LandRegisteredEvent.OutputTuple,
      LandRegisteredEvent.OutputObject
    >;
    LandRegistered: TypedContractEvent<
      LandRegisteredEvent.InputTuple,
      LandRegisteredEvent.OutputTuple,
      LandRegisteredEvent.OutputObject
    >;

    "OwnershipTransferred(uint256,address,address,uint256)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RegistrarAdded(address,address)": TypedContractEvent<
      RegistrarAddedEvent.InputTuple,
      RegistrarAddedEvent.OutputTuple,
      RegistrarAddedEvent.OutputObject
    >;
    RegistrarAdded: TypedContractEvent<
      RegistrarAddedEvent.InputTuple,
      RegistrarAddedEvent.OutputTuple,
      RegistrarAddedEvent.OutputObject
    >;

    "RegistrarRemoved(address,address)": TypedContractEvent<
      RegistrarRemovedEvent.InputTuple,
      RegistrarRemovedEvent.OutputTuple,
      RegistrarRemovedEvent.OutputObject
    >;
    RegistrarRemoved: TypedContractEvent<
      RegistrarRemovedEvent.InputTuple,
      RegistrarRemovedEvent.OutputTuple,
      RegistrarRemovedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
  };
}
